/**
 * Stable API `code` values for auth-related 401/403/400 responses.
 * Keep in sync with Attendance_App client handling and docs/auth-error-codes.md
 */
module.exports = {
  // 400
  MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
  RATE_LIMIT_LOGIN: 'RATE_LIMIT_LOGIN',
  RATE_LIMIT_REFRESH: 'RATE_LIMIT_REFRESH',

  // 401 — access / protect
  NO_TOKEN: 'NO_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_ENDED_PLATFORM_SWITCH: 'SESSION_ENDED_PLATFORM_SWITCH',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  TOKEN_VERSION_STALE: 'TOKEN_VERSION_STALE',

  // 401 — refresh
  NO_REFRESH_TOKEN: 'NO_REFRESH_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  TOKEN_THEFT_DETECTED: 'TOKEN_THEFT_DETECTED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_ERROR: 'REFRESH_ERROR',

  // 403
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
};
